version: '3.7'

services:
  custom-app:
    container_name: custom-app
    image: lizavetka378/app:v2
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db


  db:
    container_name: db
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
    networks:
      - backend

networks:
  backend:
    driver: bridge